### ISSUE TITLE
Add option to stop animation after a specified period

### ISSUE THREAD

**Issue by clive107** [i-protoss/wave#12]
**Is your feature request related to a problem? Please describe.**
For now, the **duration** that passed into the **WaveWidget** is not being used. It would be good to be able to stop animations after a specified duration.

**Describe the solution you'd like**
Add a property **isLoop**(bool) to the **WaveWidget** with default true. If **isLoop** is false, stop the animations after the specified duration.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by vladmazur** [comment]
I've added pause and start methods here: https://github.com/glorylab/wave/pull/45
