### ISSUE TITLE
Channel dev, 1.24.0-7.0.pre

### ISSUE THREAD

**Issue by danieramiz** [i-protoss/wave#22]
**Describe the bug**
../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:46:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'colors` or `gradients');          
            ^^^^^^^^^^^^^^                                              
../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:60:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'durations');                      
            ^^^^^^^^^^^^^^                                              
../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:66:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'heightPercentages');  

**To Reproduce**
Run your example project

**Expected behavior**
Run without errors

**Smartphone (please complete the following information):**
WEB

**Additional context**
flutter channel DEV

**Comment by emsaints** [comment]
Also happens on latest MASTER channel.

**Comment by ghenry** [comment]
Same here. Trying on dev channel for Windows desktop as per https://flutter.dev/desktop#set-up

Any updates or workarounds?

**Comment by AbdOoSaed** [comment]
use this fork until the package gets an update

```yaml
  wave:
    git:
      url: git://github.com/searchy2/wave.git
```

**Comment by RockerFlower** [comment]
Apologies for the delayed response. 

Version `0.2.0` is migrated to null safety now.

```
dependencies:
  wave: ^0.2.0
```
