### ISSUE TITLE
Error on `throwNullError`

### ISSUE THREAD

**Issue by dvlop** [i-protoss/wave#24]
**Describe the bug**
```
Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:46:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'colors` or `gradients');
            ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:60:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'durations');
            ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:66:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'heightPercentages');
```

**To Reproduce**
1. When try run code on android studio
2. flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-8.0.pre.178, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.0)
[✓] Connected device (2 available)

• No issues found!
```

**Expected behavior**
Can't run app on android studio

**Screenshots**
![Screen Shot 2020-11-10 at 14 52 16](https://user-images.githubusercontent.com/1873578/98676508-5da92500-2364-11eb-9281-6c9e232d34f3.png)

**Smartphone (please complete the following information):**
 - Device: Android SDK build for x86

**Additional context**
Crashed on build application

**Comment by hasanbasri1993** [comment]
same, but i try to edit /.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart 
remove line throwNullError

**Comment by searchy2** [comment]
Created a PR to fix the issue. 
With the new null safe builds, the Dart language no longer supports accessing functions in initializers.

**Comment by woshitom** [comment]
> same, but i try to edit /.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart
> remove line throwNullError

Hi, where exactly is this file please?

**Comment by AbdOoSaed** [comment]
use this fork until the package gets an update

```yaml
  wave:
    git:
      url: git://github.com/searchy2/wave.git
```

**Comment by calistus** [comment]
@AbdOoSaed Solution works
