### ISSUE TITLE
after flutter upgrade 2 the package throw this error 

### ISSUE THREAD

**Issue by eslam-elswesy** [i-protoss/wave#30]
**Describe the bug**
 Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'colors` or `gradients');

**Comment by calistus** [comment]
Samething here

**Comment by HektorCyC** [comment]
Add this to your pubspec.yaml

`  wave:
    git:
      url: git://github.com/searchy2/wave.git
`

**Comment by calistus** [comment]
Thanks. this works

**Comment by RockerFlower** [comment]
Apologies for the delayed response. 

Version `0.2.0` is migrated to null safety now.

```
dependencies:
  wave: ^0.2.0
```
